import { ProjectRisk } from '@/types/risk'

export const MOCK_RISKS: ProjectRisk[] = [
  {
    risk_id: 'R-GREEN-TH-001',
    project_id: 'ppp-001',
    title: 'เปิดประมูลตามกฎหมายไม่สามารถหาผู้ลงทุนได้',
    description: 'การเปิดประมูลตามกฎหมายไม่สามารถหาผู้ลงทุนได้',
    category: 'Strategic / Partnering',
    source_framework: 'GIHub',
    phase: 'planning',
    probability: 'medium',
    impact: 'high',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'ต้องเปลี่ยนไปใช้การเจรจากับผู้รับสัมปทานรายเดิม',
    status: 'occurred',
    occurred_date: '2019-01-01',
    pattern_id: 'RP-STRAT-PROC',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-GREEN-TH-002',
    project_id: 'ppp-002',
    title: 'โครงการมีเจ้าของ 2 หน่วยงานทำให้บริหารไม่เป็นเอกภาพ',
    description: 'สายสีเขียวมีเจ้าของโครงการ 2 หน่วยงาน ทำให้การบริหารจัดการไม่เป็นเอกภาพ ต้องใช้มติ ครม. และคำสั่งพิเศษ',
    category: 'Strategic / Partnering',
    source_framework: 'GIHub',
    phase: 'operation',
    probability: 'high',
    impact: 'high',
    owner: 'Shared',
    mitigation: 'ตั้งคณะกรรมการบริหารร่วมและโครงสร้างกำกับเดียว',
    status: 'monitoring',
    occurred_date: '',
    pattern_id: 'RP-STRAT-MULTIAGENCY',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-GREEN-TH-003',
    project_id: 'ppp-003',
    title: 'ขยายสัมปทานโดยใช้คำสั่งพิเศษแทนขั้นตอน PPP',
    description: 'การขยายสัมปทานใช้คำสั่งหัวหน้าคสช. แทนการดำเนินการตามขั้นตอน พ.ร.บ. PPP ครบถ้วน',
    category: 'Change in law',
    source_framework: 'GIHub',
    phase: 'planning',
    probability: 'medium',
    impact: 'high',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'กำหนด checklist การปฏิบัติตามกฎหมาย PPP',
    status: 'occurred',
    occurred_date: '2019-04-01',
    pattern_id: 'RP-LAW-BYPASS',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-GREEN-TH-004',
    project_id: 'ppp-004',
    title: 'ภาระหนี้และดอกเบี้ยจากส่วนต่อขยายสูง',
    description: 'กทม. มีหนี้และภาระดอกเบี้ยสูงจากการก่อสร้างส่วนต่อขยาย ต้องเจรจาโอนภาระไปยังเอกชนคู่สัญญา',
    category: 'Financial markets',
    source_framework: 'GIHub',
    phase: 'finance',
    probability: 'high',
    impact: 'high',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'วางแผนโครงสร้างหนี้และรีไฟแนนซ์',
    status: 'monitoring',
    occurred_date: '',
    pattern_id: 'RP-FIN-DEBT',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-GREEN-TH-005',
    project_id: 'ppp-005',
    title: 'ประกาศค่าโดยสารสูงสุดถูกต่อต้านหนัก',
    description: 'การประกาศเก็บค่าโดยสารสูงสุด 104 บาท ถูกต่อต้านอย่างหนักและต้องเลื่อนออกไป',
    category: 'Social',
    source_framework: 'GIHub',
    phase: 'operation',
    probability: 'medium',
    impact: 'medium',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'ทำรับฟังความคิดเห็นและปรับโครงสร้างค่าโดยสาร',
    status: 'occurred',
    occurred_date: '2023-01-01',
    pattern_id: 'RP-SOC-FARE',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-GREEN-TH-006',
    project_id: 'ppp-006',
    title: 'ถูกศาลสั่งให้ชำระหนี้ค่าเดินรถและซ่อมบำรุง',
    description: 'ศาลปกครองสั่งให้ชำระหนี้ค่าเดินรถและซ่อมบำรุงให้เอกชนหลายหมื่นล้านบาท',
    category: 'MAGA',
    source_framework: 'GIHub',
    phase: 'finance',
    probability: 'medium',
    impact: 'high',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'เพิ่มระบบควบคุมการชำระเงินตามสัญญา',
    status: 'occurred',
    occurred_date: '2023-06-01',
    pattern_id: 'RP-MAGA-PAYMENT',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-BLUE-TH-001',
    project_id: 'PPP-สายสีน้ำเงิน',
    title: 'เปลี่ยนรูปแบบ PPP หลัง ครม. อนุมัติ',
    description: 'เดิม ครม. เห็นชอบ PPP Gross Cost แต่ภายหลังเปลี่ยนเป็น PPP Net Cost',
    category: 'Change in law',
    source_framework: 'GIHub',
    phase: 'planning',
    probability: 'medium',
    impact: 'medium',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'ตรึงรูปแบบ PPP ก่อนเริ่มคัดเลือกเอกชน',
    status: 'occurred',
    occurred_date: '2017-01-01',
    pattern_id: 'RP-LAW-MODEL',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-BLUE-TH-002',
    project_id: 'PPP-สายสีน้ำเงิน',
    title: 'เปลี่ยนจากประมูลเป็นเจรจาตรงกับเอกชนรายเดิม',
    description: 'คณะกรรมการคัดเลือกไม่ใช้วิธีประมูล แต่เปลี่ยนเป็นเจรจาตรงกับเอกชนรายเดิม',
    category: 'Strategic / Partnering',
    source_framework: 'GIHub',
    phase: 'planning',
    probability: 'medium',
    impact: 'high',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'กำหนดเงื่อนไขกรณียกเว้นการประมูลให้ชัดเจน',
    status: 'occurred',
    occurred_date: '2017-02-01',
    pattern_id: 'RP-STRAT-DIRECT',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-BLUE-TH-003',
    project_id: 'PPP-สายสีน้ำเงิน',
    title: 'ส่วนต่อขยายผู้โดยสารน้อยกว่าคาด',
    description: 'ส่วนต่อขยายมีผู้โดยสารน้อย ต้องใช้รายได้ส่วนหลักมาชดเชย',
    category: 'Demand',
    source_framework: 'GIHub',
    phase: 'operation',
    probability: 'high',
    impact: 'high',
    owner: 'Shared',
    mitigation: 'ใช้ประมาณการผู้โดยสารแบบ conservative',
    status: 'occurred',
    occurred_date: '2021-01-01',
    pattern_id: 'RP-DEMAND-LOW',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-PURPLE-TH-001',
    project_id: 'PPP-สายสีม่วง',
    title: 'ช่วงสั้นลงทุนไม่คุ้มค่า',
    description: 'ช่วงเตาปูน–บางซื่อ ต้นทุนสูง รายได้น้อย จึงยุติและผนวกรวมกับโครงการอื่น',
    category: 'Financial markets',
    source_framework: 'GIHub',
    phase: 'planning',
    probability: 'medium',
    impact: 'high',
    owner: 'Shared',
    mitigation: 'วิเคราะห์ความคุ้มค่าแบบรวมช่วง',
    status: 'occurred',
    occurred_date: '2016-01-01',
    pattern_id: 'RP-FIN-SHORTSEG',
    last_updated: '2026-01-31',
  },
  {
    risk_id: 'R-PURPLE-TH-002',
    project_id: 'PPP-สายสีม่วง',
    title: 'เปิดเดินรถไม่ต่อเนื่องเกิดสถานีว่าง',
    description: 'เปิดเดินรถก่อนแต่สายเชื่อมยังไม่เสร็จ ทำให้เกิดสถานีว่าง',
    category: 'Operating',
    source_framework: 'GIHub',
    phase: 'operation',
    probability: 'medium',
    impact: 'high',
    owner: 'หน่วยงานรัฐ',
    mitigation: 'วางแผนเปิดใช้แบบเชื่อมต่อครบโครงข่าย',
    status: 'occurred',
    occurred_date: '2016-08-01',
    pattern_id: 'RP-OPER-GAP',
    last_updated: '2026-01-31',
  },
]

/** Match risk to project by project_id, or by project id/title (e.g. title contains "สายสีเขียว") */
export function getRisksForProject(
  risks: ProjectRisk[],
  projectId: string,
  projectTitle: string
): ProjectRisk[] {
  const normalizedTitle = (projectTitle || '').trim()
  return risks.filter((r) => {
    if (r.project_id === projectId) return true
    const code = r.project_id.replace(/^PPP-/, '')
    return code && normalizedTitle.includes(code)
  })
}
