/** Risk categories for dropdown (display category_name, save category_id) */
export const RISK_CATEGORIES = [
  { category_id: 'C01', category_code: 'LAND_SITE', category_name: 'Land availability, access & site', description_en: 'The risk associated with selecting land suitable for the project; providing it with good title and free of encumbrances; addressing indigenous rights; obtaining necessary planning approvals; providing access to the site; site security; and site and existing asset condition.', description_th: 'ความเสี่ยงที่เกี่ยวกับการได้มาซึ่งที่ดินที่เหมาะสม กรรมสิทธิ์ที่ดินที่ปราศจากภาระผูกพัน การจัดการสิทธิ์ชนพื้นเมือง การได้รับอนุมัติผังเมือง การเข้าถึงพื้นที่ ความปลอดภัยในพื้นที่ และสภาพสินทรัพย์เดิม' },
  { category_id: 'C02', category_code: 'SOCIAL', category_name: 'Social', description_en: 'The risk associated with the project impact on adjacent properties and affected people (including public protest and unrest); resettlement; indigenous land rights; and industrial action.', description_th: 'ความเสี่ยงจากผลกระทบของโครงการต่อทรัพย์สินข้างเคียงและประชาชนที่ได้รับผลกระทบ รวมถึงการประท้วง การโยกย้ายถิ่นฐาน สิทธิ์ที่ดินชนพื้นเมือง และการนัดหยุดงาน' },
  { category_id: 'C03', category_code: 'ENVIRONMENTAL', category_name: 'Environmental', description_en: 'The risk associated with pre-existing conditions; obtaining consents; compliance with laws; conditions caused by the project; external events; and climate change.', description_th: 'ความเสี่ยงด้านสิ่งแวดล้อม ได้แก่ สภาพแวดล้อมก่อนเริ่มโครงการ การได้รับความยินยอม การปฏิบัติตามกฎหมาย ผลกระทบจากโครงการ เหตุการณ์ภายนอก และการเปลี่ยนแปลงสภาพภูมิอากาศ' },
  { category_id: 'C04', category_code: 'DESIGN', category_name: 'Design', description_en: 'The risk that the project design is not suitable for the purpose required; approval of design; and changes.', description_th: 'ความเสี่ยงที่การออกแบบโครงการไม่เหมาะสมกับวัตถุประสงค์ที่ต้องการ รวมถึงการขออนุมัติแบบและการเปลี่ยนแปลงแบบ' },
  { category_id: 'C05', category_code: 'CONSTRUCTION', category_name: 'Construction', description_en: 'The risk of construction costs exceeding modelled costs; completion delays;  project management; interface;  quality standards compliance; health and safety; defects; intellectual property rights compliance; industrial action; and vandalism.', description_th: 'ความเสี่ยงด้านต้นทุนก่อสร้างที่เกินงบประมาณ ความล่าช้าในการแล้วเสร็จ การบริหารโครงการ การประสานงาน มาตรฐานคุณภาพ ความปลอดภัย ข้อบกพร่อง ทรัพย์สินทางปัญญา การนัดหยุดงาน และการก่อกวน' },
  { category_id: 'C06', category_code: 'VARIATIONS', category_name: 'Variations', description_en: 'The risk of changes requested by either party to the service which affect construction or operation.', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงบริการที่ร้องขอโดยฝ่ายใดฝ่ายหนึ่ง ซึ่งส่งผลกระทบต่อการก่อสร้างหรือการดำเนินงาน' },
  { category_id: 'C07', category_code: 'OPERATING', category_name: 'Operating', description_en: 'The risk of events affecting performance or increasing costs beyond modelled costs; performance standards and price; availability of resources; intellectual property rights compliance; health and safety; compliance with maintenance standards; industrial action; and vandalism.', description_th: 'ความเสี่ยงจากเหตุการณ์ที่กระทบต่อประสิทธิภาพหรือเพิ่มต้นทุนดำเนินงาน มาตรฐานการให้บริการและราคา ความพร้อมของทรัพยากร ทรัพย์สินทางปัญญา ความปลอดภัย มาตรฐานการบำรุงรักษา การนัดหยุดงาน และการก่อกวน' },
  { category_id: 'C08', category_code: 'DEMAND', category_name: 'Demand', description_en: 'The risk of traffic levels being different to forecast levels; the consequences for revenue and costs; and government support measures.', description_th: 'ความเสี่ยงจากปริมาณการใช้บริการที่แตกต่างจากที่พยากรณ์ไว้ ผลกระทบต่อรายได้และต้นทุน รวมถึงมาตรการสนับสนุนของรัฐบาล' },
  { category_id: 'C09', category_code: 'FIN_MARKET', category_name: 'Financial markets', description_en: 'The risk of inflation; exchange rate fluctuation; interest rate fluctuation; unavailability of insurance; and refinancing.', description_th: 'ความเสี่ยงด้านตลาดการเงิน ได้แก่ เงินเฟ้อ ความผันผวนของอัตราแลกเปลี่ยน ความผันผวนของอัตราดอกเบี้ย การขาดแคลนประกันภัย และการรีไฟแนนซ์' },
  { category_id: 'C10', category_code: 'STRATEGIC', category_name: 'Strategic / Partnering', description_en: 'The risk of the Private Partner and/or its sub-contractors not being the right choice to deliver the project; Contracting Authority intervention in the project; ownership changes; and disputes.', description_th: 'ความเสี่ยงจากการเลือกพันธมิตรภาคเอกชนและผู้รับเหมาที่ไม่เหมาะสม การแทรกแซงของหน่วยงานรัฐ การเปลี่ยนแปลงกรรมสิทธิ์ และข้อพิพาท' },
  { category_id: 'C11', category_code: 'DISRUPT_TECH', category_name: 'Disruptive technology', description_en: 'The risk that a new emerging technology unexpectedly displaces an established technology or the risk of obsolescence of equipment or materials used.', description_th: 'ความเสี่ยงจากเทคโนโลยีใหม่ที่เข้ามาแทนที่เทคโนโลยีที่ใช้อยู่โดยไม่คาดคิด หรือความล้าสมัยของอุปกรณ์และวัสดุที่ใช้ในโครงการ' },
  { category_id: 'C12', category_code: 'FORCE_MAJEURE', category_name: 'Force majeure', description_en: 'The risk that unexpected events occur that are beyond the control of the parties and delay or prevent performance.', description_th: 'ความเสี่ยงจากเหตุการณ์ที่ไม่คาดคิดและอยู่นอกเหนือการควบคุมของคู่สัญญา ซึ่งอาจทำให้ล่าช้าหรือไม่สามารถปฏิบัติตามสัญญาได้' },
  { category_id: 'C13', category_code: 'POLITICAL', category_name: 'Political', description_en: 'Risks arising from government actions, policy changes, regulatory instability, or political interference that may affect project approvals, contractual conditions, or overall project continuity.', description_th: 'ความเสี่ยงจากการดำเนินการของรัฐบาล การเปลี่ยนแปลงนโยบาย ความไม่แน่นอนของกฎระเบียบ หรือการแทรกแซงทางการเมืองที่ส่งผลต่อการอนุมัติโครงการและความต่อเนื่องโดยรวม' },
  { category_id: 'C14', category_code: 'LAW', category_name: 'Law', description_en: 'The risk of compliance with applicable law; and changes in law affecting performance of the project or the Private Partner\'s costs.', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามกฎหมายที่บังคับใช้ และการเปลี่ยนแปลงกฎหมายที่ส่งผลต่อการดำเนินโครงการหรือต้นทุนของเอกชนคู่สัญญา' },
  { category_id: 'C15', category_code: 'EARLY_TERMINATION', category_name: 'Early termination', description_en: 'The risk of a project being terminated before its natural expiry on various grounds; the financial consequences of such termination; and the strength of the Contracting Authority\'s payment covenant.', description_th: 'ความเสี่ยงจากการยกเลิกโครงการก่อนกำหนดด้วยเหตุผลต่าง ๆ ผลกระทบทางการเงินจากการยกเลิก และความแข็งแกร่งของภาระผูกพันในการชำระเงินของหน่วยงานรัฐ' },
  { category_id: 'C16', category_code: 'HANDBACK_COND', category_name: 'Condition at handback', description_en: 'The risk of deterioration of the project assets/land during the life of the PPP and the risk that the project assets/land are not in the contractually required condition at the time of handback to the Contracting Authority.', description_th: 'ความเสี่ยงจากการเสื่อมสภาพของสินทรัพย์หรือที่ดินโครงการตลอดอายุ PPP และความเสี่ยงที่สินทรัพย์จะไม่อยู่ในสภาพที่กำหนดตามสัญญาเมื่อถึงเวลาส่งคืนให้หน่วยงานรัฐ' },
  { category_id: 'C17', category_code: 'PROJECT_SELECTION', category_name: 'Project selected', description_en: 'Project selection refers to the process of choosing PPP projects that are socially acceptable, technically feasible, and aligned with public demand, where risks may arise from public opposition, inappropriate tendering, or poor assessment of project suitability.', description_th: 'ความเสี่ยงในกระบวนการคัดเลือกโครงการ PPP ที่ต้องเป็นที่ยอมรับของสังคม มีความเป็นไปได้ทางเทคนิค และสอดคล้องกับความต้องการสาธารณะ โดยความเสี่ยงอาจเกิดจากการต่อต้านของประชาชน การประมูลที่ไม่เหมาะสม หรือการประเมินความเหมาะสมที่บกพร่อง' },
  { category_id: 'C18', category_code: 'RELATIONSHIP', category_name: 'Relationship', description_en: 'Relationship refers to the quality of collaboration, coordination, and mutual understanding between public and private partners in PPP projects, where differences in working methods, responsibilities, and communication can create significant risks.', description_th: 'ความเสี่ยงด้านคุณภาพของความร่วมมือ การประสานงาน และความเข้าใจร่วมกันระหว่างภาครัฐและเอกชนใน PPP โดยความแตกต่างในวิธีการทำงาน ความรับผิดชอบ และการสื่อสาร อาจสร้างความเสี่ยงอย่างมีนัยสำคัญ' },
  { category_id: 'C19', category_code: 'PROJECT_FINANCE', category_name: 'Project finance', description_en: 'Project finance refers to the financial structure and attractiveness of a PPP project to investors, including the availability of financing, cost of capital, and the project\'s ability to generate sufficient returns to support long-term investment.', description_th: 'ความเสี่ยงด้านโครงสร้างทางการเงินและความน่าดึงดูดของโครงการ PPP ต่อนักลงทุน รวมถึงความพร้อมของแหล่งเงินทุน ต้นทุนเงินทุน และความสามารถของโครงการในการสร้างผลตอบแทนเพียงพอเพื่อรองรับการลงทุนระยะยาว' },
  { category_id: 'C20', category_code: 'PROCUREMENT', category_name: 'Procurement risks', description_en: 'Risks related to the tendering and contracting process, including non-transparent selection procedures, uncompetitive bidding, poor negotiation, or delays in award decisions that may impact project performance and fairness.', description_th: 'ความเสี่ยงในกระบวนการประมูลและการทำสัญญา รวมถึงขั้นตอนการคัดเลือกที่ขาดความโปร่งใส การประมูลที่ไม่มีการแข่งขัน การเจรจาที่ไม่มีประสิทธิภาพ หรือความล่าช้าในการตัดสินใจมอบสัญญา' },
] as const

/** Risk factors for dropdown (display factor_name, save factor_id) */
export const RISK_FACTORS = [
  { factor_id: 'F01', factor_name: 'Access to the site and associated infrastructure', description_th: 'ความเสี่ยงด้านการเข้าถึงพื้นที่โครงการและโครงสร้างพื้นฐานที่เกี่ยวข้อง เช่น ถนน ระบบสาธารณูปโภค และเส้นทางเข้าออก' },
  { factor_id: 'F02', factor_name: 'Approval of designs', description_th: 'ความเสี่ยงจากความล่าช้าหรือการปฏิเสธในการอนุมัติแบบแปลนจากหน่วยงานที่เกี่ยวข้อง' },
  { factor_id: 'F03', factor_name: 'Asset Ownership Risk (at the end of the contract)', description_th: 'ความเสี่ยงด้านกรรมสิทธิ์ในสินทรัพย์โครงการเมื่อสิ้นสุดสัญญา ว่าจะตกเป็นของฝ่ายใด' },
  { factor_id: 'F04', factor_name: 'Availability of labor/materials', description_th: 'ความเสี่ยงจากการขาดแคลนแรงงานหรือวัสดุที่จำเป็นสำหรับการก่อสร้างหรือดำเนินงาน' },
  { factor_id: 'F05', factor_name: 'Change in Contracting Authority ownership/status', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงกรรมสิทธิ์หรือสถานะขององค์กรภาครัฐที่เป็นคู่สัญญา' },
  { factor_id: 'F06', factor_name: 'Change in law (and taxation)', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงกฎหมายและภาษีที่ส่งผลกระทบต่อต้นทุนหรือการดำเนินงานของโครงการ' },
  { factor_id: 'F07', factor_name: 'Change in Private Partner ownership', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงผู้ถือหุ้นหรือกรรมสิทธิ์ของเอกชนคู่สัญญาที่อาจกระทบต่อการดำเนินโครงการ' },
  { factor_id: 'F08', factor_name: 'Change of scope', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงขอบเขตของโครงการที่ส่งผลต่อต้นทุน ระยะเวลา และคุณภาพ' },
  { factor_id: 'F09', factor_name: 'Changes in industrial code of practices', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงมาตรฐานหรือข้อบังคับในอุตสาหกรรมที่โครงการต้องปฏิบัติตาม' },
  { factor_id: 'F10', factor_name: 'Changes to design', description_th: 'ความเสี่ยงจากการปรับเปลี่ยนแบบแปลนในระหว่างดำเนินโครงการ ซึ่งอาจเพิ่มต้นทุนหรือทำให้ล่าช้า' },
  { factor_id: 'F11', factor_name: 'Climate change event', description_th: 'ความเสี่ยงจากเหตุการณ์ที่เกิดจากการเปลี่ยนแปลงสภาพภูมิอากาศ เช่น อุทกภัย ภัยแล้ง หรือคลื่นความร้อน' },
  { factor_id: 'F12', factor_name: 'Community and businesses', description_th: 'ความเสี่ยงจากผลกระทบของโครงการต่อชุมชนและธุรกิจในพื้นที่ รวมถึงการประท้วงหรือการต่อต้าน' },
  { factor_id: 'F13', factor_name: 'Competition risk', description_th: 'ความเสี่ยงจากการแข่งขันของผู้ให้บริการรายอื่นที่อาจดึงความต้องการและส่งผลต่อรายได้ของโครงการ' },
  { factor_id: 'F14', factor_name: 'Compliance with applicable law', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามกฎหมายและข้อบังคับที่เกี่ยวข้องกับโครงการ' },
  { factor_id: 'F15', factor_name: 'Compliance with environmental consents and laws', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามใบอนุญาตด้านสิ่งแวดล้อมและกฎหมายสิ่งแวดล้อมที่บังคับใช้' },
  { factor_id: 'F16', factor_name: 'Condition At Handback Risk', description_th: 'ความเสี่ยงด้านสภาพของสินทรัพย์โครงการที่อาจไม่เป็นไปตามมาตรฐานที่กำหนดในสัญญาเมื่อถึงเวลาส่งคืน' },
  { factor_id: 'F17', factor_name: 'Condition of facility', description_th: 'ความเสี่ยงด้านสภาพของสิ่งอำนวยความสะดวกที่เสื่อมโทรมหรือไม่เพียงพอ ส่งผลต่อคุณภาพการให้บริการ' },
  { factor_id: 'F18', factor_name: 'Conflicting or imperfect contract', description_th: 'ความเสี่ยงจากข้อขัดแย้งหรือความบกพร่องในสัญญาที่อาจนำไปสู่ข้อพิพาทระหว่างคู่สัญญา' },
  { factor_id: 'F19', factor_name: 'Considerations', description_th: 'ความเสี่ยงจากปัจจัยและเงื่อนไขพิเศษต่าง ๆ ที่ต้องพิจารณาในการดำเนินโครงการ PPP' },
  { factor_id: 'F20', factor_name: 'Consortium inability', description_th: 'ความเสี่ยงจากการที่กลุ่มกิจการร่วมค้าไม่สามารถปฏิบัติตามพันธกรณีที่ตกลงไว้ได้' },
  { factor_id: 'F21', factor_name: 'Contracting Authority default termination', description_th: 'ความเสี่ยงจากการที่หน่วยงานรัฐผิดนัดชำระหนี้หรือผิดสัญญาจนนำไปสู่การยกเลิกสัญญา' },
  { factor_id: 'F22', factor_name: 'Contractor failure/Capability of SPV', description_th: 'ความเสี่ยงจากความล้มเหลวของผู้รับเหมาหลักหรือขีดความสามารถที่ไม่เพียงพอของบริษัทพิเศษเฉพาะกิจ (SPV)' },
  { factor_id: 'F23', factor_name: 'Contractual termination provisions', description_th: 'ความเสี่ยงจากเงื่อนไขการยกเลิกสัญญาที่ไม่ชัดเจนหรือไม่เป็นธรรม ซึ่งอาจสร้างความเสียหายต่อคู่สัญญาฝ่ายใดฝ่ายหนึ่ง' },
  { factor_id: 'F24', factor_name: 'Corruption and lack of respect for law', description_th: 'ความเสี่ยงจากการทุจริตคอร์รัปชัน การติดสินบน และการไม่เคารพต่อกฎหมายในกระบวนการดำเนินโครงการ' },
  { factor_id: 'F25', factor_name: 'Cost increases', description_th: 'ความเสี่ยงจากต้นทุนโครงการที่เพิ่มขึ้นเกินกว่าประมาณการ เนื่องจากราคาวัสดุ แรงงาน หรือปัจจัยอื่น' },
  { factor_id: 'F26', factor_name: 'Cultural differences between main stakeholders', description_th: 'ความเสี่ยงจากความแตกต่างทางวัฒนธรรมและแนวคิดระหว่างผู้มีส่วนได้ส่วนเสียหลักที่ส่งผลต่อการทำงานร่วมกัน' },
  { factor_id: 'F27', factor_name: 'Defects and defective materials', description_th: 'ความเสี่ยงจากข้อบกพร่องในงานก่อสร้างหรือการใช้วัสดุที่ไม่ได้มาตรฐาน ซึ่งส่งผลต่อความทนทานและความปลอดภัย' },
  { factor_id: 'F28', factor_name: 'Delay in approval / permit', description_th: 'ความเสี่ยงจากความล่าช้าในการขออนุมัติหรือใบอนุญาตต่าง ๆ จากหน่วยงานราชการ' },
  { factor_id: 'F29', factor_name: 'Delay in commencement of operations', description_th: 'ความเสี่ยงจากความล่าช้าในการเปิดให้บริการหรือเริ่มต้นดำเนินงานตามกำหนด' },
  { factor_id: 'F30', factor_name: 'Delay in financial closure', description_th: 'ความเสี่ยงจากความล่าช้าในการปิดการจัดหาเงินทุน ซึ่งอาจทำให้โครงการไม่สามารถเริ่มต้นได้ตามแผน' },
  { factor_id: 'F31', factor_name: 'Delay in payment of anuity', description_th: 'ความเสี่ยงจากความล่าช้าในการชำระเงินค่าตอบแทนตามสัญญาจากหน่วยงานรัฐ' },
  { factor_id: 'F32', factor_name: 'Different working methods/know-how between partners', description_th: 'ความเสี่ยงจากความแตกต่างในวิธีการทำงานและองค์ความรู้ระหว่างพันธมิตรภาครัฐและเอกชน' },
  { factor_id: 'F33', factor_name: 'Disputes', description_th: 'ความเสี่ยงจากข้อพิพาทระหว่างคู่สัญญาที่อาจนำไปสู่การฟ้องร้องและส่งผลต่อการดำเนินโครงการ' },
  { factor_id: 'F34', factor_name: 'Disruptive Technology Risk', description_th: 'ความเสี่ยงจากเทคโนโลยีพลิกผันที่เข้ามาแทนที่เทคโนโลยีปัจจุบัน ทำให้โครงการล้าสมัยหรือสูญเสียความสามารถในการแข่งขัน' },
  { factor_id: 'F35', factor_name: 'Environmental conditions caused by the project', description_th: 'ความเสี่ยงจากผลกระทบด้านสิ่งแวดล้อมที่เกิดจากการก่อสร้างหรือดำเนินงานของโครงการ' },
  { factor_id: 'F36', factor_name: 'Exchange rate fluctuation', description_th: 'ความเสี่ยงจากความผันผวนของอัตราแลกเปลี่ยนเงินตราต่างประเทศที่กระทบต้นทุนและรายได้ของโครงการ' },
  { factor_id: 'F37', factor_name: 'Existing asset condition', description_th: 'ความเสี่ยงจากสภาพของสินทรัพย์เดิมที่ไม่เหมาะสมหรือเสื่อมโทรม ซึ่งอาจเพิ่มต้นทุนในการพัฒนา' },
  { factor_id: 'F38', factor_name: 'External environmental events', description_th: 'ความเสี่ยงจากเหตุการณ์ด้านสิ่งแวดล้อมภายนอกที่ไม่สามารถควบคุมได้ เช่น น้ำท่วม แผ่นดินไหว หรือพายุรุนแรง' },
  { factor_id: 'F39', factor_name: 'Financial attraction of project to investors', description_th: 'ความเสี่ยงจากความไม่น่าดึงดูดทางการเงินของโครงการที่ทำให้ยากต่อการระดมทุนจากนักลงทุน' },
  { factor_id: 'F40', factor_name: 'Financiers unwilling to take high risk', description_th: 'ความเสี่ยงจากการที่สถาบันการเงินหรือผู้ให้เงินทุนไม่ยินดีรับความเสี่ยงสูงในโครงการ' },
  { factor_id: 'F41', factor_name: 'Fluctuation of material cost (by government)', description_th: 'ความเสี่ยงจากการผันผวนของราคาวัสดุก่อสร้างอันเนื่องมาจากนโยบายหรือการแทรกแซงของภาครัฐ' },
  { factor_id: 'F42', factor_name: 'Fluctuation of material cost (by private)', description_th: 'ความเสี่ยงจากการผันผวนของราคาวัสดุก่อสร้างอันเนื่องมาจากกลไกตลาดและปัจจัยภาคเอกชน' },
  { factor_id: 'F43', factor_name: 'Force Majeure and Uninsurability termination', description_th: 'ความเสี่ยงจากเหตุสุดวิสัยและการไม่สามารถจัดทำประกันภัยได้ จนนำไปสู่การยกเลิกสัญญาโครงการ' },
  { factor_id: 'F44', factor_name: 'Force majeure consequences', description_th: 'ความเสี่ยงจากผลกระทบที่ตามมาจากเหตุการณ์สุดวิสัย เช่น การหยุดชะงักของโครงการและต้นทุนที่เพิ่มขึ้น' },
  { factor_id: 'F45', factor_name: 'Force majeure events', description_th: 'ความเสี่ยงจากเหตุการณ์สุดวิสัยที่อยู่นอกเหนือการควบคุม เช่น ภัยธรรมชาติ สงคราม การก่อการร้าย หรือโรคระบาด' },
  { factor_id: 'F46', factor_name: 'Frequency of maintenance', description_th: 'ความเสี่ยงจากความถี่ในการบำรุงรักษาที่มากเกินคาดการณ์ ส่งผลต่อต้นทุนดำเนินงานและความพร้อมให้บริการ' },
  { factor_id: 'F47', factor_name: 'General principles', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามหลักการพื้นฐานของโครงการ PPP ที่ดี รวมถึงความโปร่งใสและความรับผิดชอบ' },
  { factor_id: 'F48', factor_name: 'Government support measures', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงหรือการถอนมาตรการสนับสนุนของรัฐบาลที่โครงการพึ่งพาอยู่' },
  { factor_id: 'F49', factor_name: 'Health and safety compliance', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามมาตรฐานด้านสุขภาพและความปลอดภัยในการทำงานและการให้บริการ' },
  { factor_id: 'F50', factor_name: 'Heritage / indigenous land rights', description_th: 'ความเสี่ยงจากการอ้างสิทธิ์ในที่ดินของชนพื้นเมืองหรือมรดกทางวัฒนธรรมที่อาจขัดขวางการพัฒนาโครงการ' },
  { factor_id: 'F51', factor_name: 'Heritage / indigenous people', description_th: 'ความเสี่ยงจากผลกระทบของโครงการต่อชุมชนชนพื้นเมืองและมรดกทางวัฒนธรรมที่ต้องได้รับการคุ้มครอง' },
  { factor_id: 'F52', factor_name: 'High bidding costs', description_th: 'ความเสี่ยงจากต้นทุนการเตรียมการประมูลที่สูงเกินไป ทำให้ผู้สนใจเข้าร่วมประมูลน้อยราย' },
  { factor_id: 'F53', factor_name: 'High finance cost', description_th: 'ความเสี่ยงจากต้นทุนทางการเงินที่สูง เช่น อัตราดอกเบี้ยสูง ค่าธรรมเนียมการจัดการ และค่าใช้จ่ายการระดมทุน' },
  { factor_id: 'F54', factor_name: 'High maintenance cost', description_th: 'ความเสี่ยงจากต้นทุนการบำรุงรักษาที่สูงกว่าประมาณการ ส่งผลต่อความสามารถในการทำกำไรของโครงการ' },
  { factor_id: 'F55', factor_name: 'Higher demand than anticipated', description_th: 'ความเสี่ยงจากความต้องการใช้บริการที่สูงกว่าที่คาดการณ์ ซึ่งอาจกดดันขีดความสามารถและคุณภาพบริการ' },
  { factor_id: 'F56', factor_name: 'Inability to service debt', description_th: 'ความเสี่ยงจากการไม่สามารถชำระดอกเบี้ยหรือเงินต้นได้ตามกำหนด อันเนื่องมาจากกระแสเงินสดไม่เพียงพอ' },
  { factor_id: 'F57', factor_name: 'Inadequate allocation of responsibility and risk', description_th: 'ความเสี่ยงจากการจัดสรรความรับผิดชอบและความเสี่ยงระหว่างภาครัฐและเอกชนที่ไม่เหมาะสม' },
  { factor_id: 'F58', factor_name: 'Inadequate distribution of responsibility and risk', description_th: 'ความเสี่ยงจากการกระจายความรับผิดชอบและภาระความเสี่ยงที่ไม่สมดุลระหว่างคู่สัญญา' },
  { factor_id: 'F59', factor_name: 'Inadequate experience in PPP', description_th: 'ความเสี่ยงจากการขาดประสบการณ์และความเชี่ยวชาญของหน่วยงานรัฐหรือเอกชนในการดำเนินโครงการ PPP' },
  { factor_id: 'F60', factor_name: 'Inadequate feasibility study', description_th: 'ความเสี่ยงจากการศึกษาความเป็นไปได้ที่ไม่ครอบคลุมหรือไม่ถูกต้อง ทำให้ประมาณการต้นทุนและรายได้ผิดพลาด' },
  { factor_id: 'F61', factor_name: 'Inadequate law and supervision system', description_th: 'ความเสี่ยงจากระบบกฎหมายและกลไกการกำกับดูแล PPP ที่ไม่เพียงพอหรือไม่มีประสิทธิภาพ' },
  { factor_id: 'F62', factor_name: 'Inadequate negotiation period prior to initiation', description_th: 'ความเสี่ยงจากระยะเวลาการเจรจาเงื่อนไขสัญญาก่อนเริ่มโครงการที่ไม่เพียงพอ นำไปสู่สัญญาที่บกพร่อง' },
  { factor_id: 'F63', factor_name: 'Increased operating costs and affected performance', description_th: 'ความเสี่ยงจากต้นทุนดำเนินงานที่เพิ่มขึ้นเกินงบประมาณ ส่งผลต่อประสิทธิภาพและคุณภาพการให้บริการ' },
  { factor_id: 'F64', factor_name: 'Industrial action', description_th: 'ความเสี่ยงจากการนัดหยุดงาน การประท้วง หรือการปฏิบัติการทางอุตสาหกรรมของแรงงานที่ขัดขวางโครงการ' },
  { factor_id: 'F65', factor_name: 'Inflation', description_th: 'ความเสี่ยงจากอัตราเงินเฟ้อที่ส่งผลให้ต้นทุนเพิ่มขึ้นและกัดเซาะมูลค่าที่แท้จริงของรายได้โครงการ' },
  { factor_id: 'F66', factor_name: 'Insolvency/default of subcontractors and supplied', description_th: 'ความเสี่ยงจากการล้มละลายหรือผิดนัดชำระหนี้ของผู้รับเหมาช่วงและผู้จัดหาวัสดุ' },
  { factor_id: 'F67', factor_name: 'insufficient income', description_th: 'ความเสี่ยงจากรายได้ที่ไม่เพียงพอต่อการชำระหนี้ ดำเนินงาน และให้ผลตอบแทนแก่ผู้ลงทุน' },
  { factor_id: 'F68', factor_name: 'Intellectual property', description_th: 'ความเสี่ยงด้านทรัพย์สินทางปัญญา สิทธิบัตร และลิขสิทธิ์ที่เกี่ยวข้องกับเทคโนโลยีหรือนวัตกรรมที่ใช้ในโครงการ' },
  { factor_id: 'F69', factor_name: 'Interest rate fluctuation', description_th: 'ความเสี่ยงจากความผันผวนของอัตราดอกเบี้ยที่กระทบต้นทุนการกู้ยืมและความสามารถในการชำระหนี้' },
  { factor_id: 'F70', factor_name: 'Interface', description_th: 'ความเสี่ยงจากการประสานงานและการเชื่อมต่อระหว่างระบบหรือหน่วยงานต่าง ๆ ที่ไม่ราบรื่น' },
  { factor_id: 'F71', factor_name: 'Key planning consents', description_th: 'ความเสี่ยงจากการไม่ได้รับการอนุมัติแผนงานหลักที่จำเป็น ซึ่งอาจหยุดหรือล่าช้าการพัฒนาโครงการ' },
  { factor_id: 'F72', factor_name: 'Lack of commitment from public/private partner', description_th: 'ความเสี่ยงจากการขาดความมุ่งมั่นและความจริงจังของภาครัฐหรือเอกชนในการผลักดันโครงการ' },
  { factor_id: 'F73', factor_name: 'Lack of creditworthiness', description_th: 'ความเสี่ยงจากการขาดความน่าเชื่อถือทางการเงินของคู่สัญญา ทำให้ยากต่อการระดมทุนและการค้ำประกัน' },
  { factor_id: 'F74', factor_name: 'Lack of government guarantees', description_th: 'ความเสี่ยงจากการขาดการค้ำประกันหรือการรับประกันความเสี่ยงจากภาครัฐที่นักลงทุนต้องการ' },
  { factor_id: 'F75', factor_name: 'Lack of transparency in the bidding', description_th: 'ความเสี่ยงจากกระบวนการประมูลที่ขาดความโปร่งใส อาจนำไปสู่ข้อสงสัยและการท้าทายผลการประมูล' },
  { factor_id: 'F76', factor_name: 'Level of demand for the project', description_th: 'ความเสี่ยงจากระดับความต้องการใช้บริการที่แตกต่างอย่างมีนัยสำคัญจากการคาดการณ์ในแบบจำลองทางการเงิน' },
  { factor_id: 'F77', factor_name: 'Liability for death, personal injury, property damage and third party liability', description_th: 'ความเสี่ยงด้านความรับผิดชอบทางกฎหมายจากการเสียชีวิต การบาดเจ็บ ความเสียหายต่อทรัพย์สิน และความรับผิดต่อบุคคลที่สาม' },
  { factor_id: 'F78', factor_name: 'Low capacity of concession company', description_th: 'ความเสี่ยงจากขีดความสามารถด้านการเงิน เทคนิค และการบริหารของบริษัทผู้รับสัมปทานที่ต่ำกว่ามาตรฐาน' },
  { factor_id: 'F79', factor_name: 'Low operating productivity', description_th: 'ความเสี่ยงจากประสิทธิภาพและผลิตภาพในการดำเนินงานที่ต่ำกว่าที่คาดการณ์ ส่งผลต่อต้นทุนและคุณภาพบริการ' },
  { factor_id: 'F80', factor_name: 'Lower demand than anticipated', description_th: 'ความเสี่ยงจากความต้องการใช้บริการที่ต่ำกว่าการคาดการณ์ ส่งผลให้รายได้ไม่เพียงพอต่อการดำเนินโครงการ' },
  { factor_id: 'F81', factor_name: 'MAGA / Change in law termination', description_th: 'ความเสี่ยงจากการยกเลิกสัญญาอันเนื่องมาจากการเปลี่ยนแปลงกฎหมายอย่างมีนัยสำคัญ (Material Adverse Government Action)' },
  { factor_id: 'F82', factor_name: 'Maintenance standards', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามมาตรฐานการบำรุงรักษาที่กำหนดในสัญญา ส่งผลต่อสภาพและอายุการใช้งานของสินทรัพย์' },
  { factor_id: 'F83', factor_name: 'Market demand change', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงของความต้องการตลาดในระยะยาว เช่น การเปลี่ยนพฤติกรรมผู้บริโภคหรือเทคโนโลยีใหม่' },
  { factor_id: 'F84', factor_name: 'Market forecast error', description_th: 'ความเสี่ยงจากความผิดพลาดในการพยากรณ์ตลาดและความต้องการ ซึ่งส่งผลต่อความเป็นไปได้ทางการเงินของโครงการ' },
  { factor_id: 'F85', factor_name: 'Non-involvement of host-community', description_th: 'ความเสี่ยงจากการไม่มีส่วนร่วมของชุมชนท้องถิ่นในกระบวนการวางแผนและตัดสินใจ นำไปสู่การต่อต้าน' },
  { factor_id: 'F86', factor_name: 'Obtaining environmental consents', description_th: 'ความเสี่ยงจากความล่าช้าหรือการไม่ได้รับการอนุมัติด้านสิ่งแวดล้อมที่จำเป็นสำหรับโครงการ' },
  { factor_id: 'F87', factor_name: 'Operational resources or input risk', description_th: 'ความเสี่ยงด้านความพร้อมและต้นทุนของทรัพยากรและปัจจัยการผลิตที่จำเป็นในการดำเนินงาน' },
  { factor_id: 'F88', factor_name: 'Organisation and coordination risk', description_th: 'ความเสี่ยงด้านการจัดองค์กรภายในและการประสานงานระหว่างหน่วยงานต่าง ๆ ที่เกี่ยวข้องกับโครงการ' },
  { factor_id: 'F89', factor_name: 'Performance/ price risk', description_th: 'ความเสี่ยงจากการที่ประสิทธิภาพการให้บริการไม่เป็นไปตามมาตรฐาน หรือการกำหนดราคาที่ไม่เหมาะสม' },
  { factor_id: 'F90', factor_name: 'Permitted Contracting Authority step-in', description_th: 'ความเสี่ยงจากการที่หน่วยงานรัฐใช้สิทธิ์เข้าแทรกแซงการดำเนินงานตามเงื่อนไขสัญญา' },
  { factor_id: 'F91', factor_name: 'Political interference', description_th: 'ความเสี่ยงจากการแทรกแซงทางการเมืองที่ไม่เหมาะสม ส่งผลต่อการตัดสินใจและการดำเนินโครงการ' },
  { factor_id: 'F92', factor_name: 'Political opposition', description_th: 'ความเสี่ยงจากการต่อต้านทางการเมืองต่อโครงการจากฝ่ายค้านหรือกลุ่มผลประโยชน์ต่าง ๆ' },
  { factor_id: 'F93', factor_name: 'Poor project appraisal and selection', description_th: 'ความเสี่ยงจากการประเมินและคัดเลือกโครงการ PPP ที่ขาดความรอบคอบ นำไปสู่การดำเนินโครงการที่ไม่คุ้มค่า' },
  { factor_id: 'F94', factor_name: 'Poor public decision making process', description_th: 'ความเสี่ยงจากกระบวนการตัดสินใจของภาครัฐที่ขาดประสิทธิภาพ ความล่าช้า หรือขาดความโปร่งใส' },
  { factor_id: 'F95', factor_name: 'Poor quality of workmanship', description_th: 'ความเสี่ยงจากคุณภาพฝีมือช่างและการก่อสร้างที่ต่ำกว่ามาตรฐาน ส่งผลต่อความปลอดภัยและความทนทาน' },
  { factor_id: 'F96', factor_name: 'Pre-existing conditions', description_th: 'ความเสี่ยงจากสภาพแวดล้อม ดิน โครงสร้างพื้นฐาน หรือข้อผูกพันที่มีอยู่ก่อนเริ่มโครงการ' },
  { factor_id: 'F97', factor_name: 'Private Partner default termination', description_th: 'ความเสี่ยงจากการที่เอกชนคู่สัญญาผิดนัดพันธกรณีจนถูกบอกเลิกสัญญา ส่งผลต่อความต่อเนื่องของบริการ' },
  { factor_id: 'F98', factor_name: 'Private Partner failure/insolvency', description_th: 'ความเสี่ยงจากการล้มเหลวทางธุรกิจหรือการล้มละลายของเอกชนคู่สัญญาในระหว่างดำเนินโครงการ' },
  { factor_id: 'F99', factor_name: 'Private Partner not to be fincially or technically capable implement the project.', description_th: 'ความเสี่ยงจากการที่เอกชนคู่สัญญาขาดความสามารถทางการเงินหรือความเชี่ยวชาญทางเทคนิคที่จำเป็นสำหรับโครงการ' },
  { factor_id: 'F100', factor_name: 'Project management and interface with other works/facilities', description_th: 'ความเสี่ยงด้านการบริหารจัดการโครงการและการประสานงานกับงานก่อสร้างหรือสิ่งอำนวยความสะดวกอื่นที่ดำเนินการควบคู่กัน' },
  { factor_id: 'F101', factor_name: 'Project operation change', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงรูปแบบหรือขอบเขตการดำเนินงานโครงการที่ส่งผลต่อต้นทุนและรายได้' },
  { factor_id: 'F102', factor_name: 'Protection of geological and historical objects', description_th: 'ความเสี่ยงจากการค้นพบโบราณวัตถุหรือสิ่งสำคัญทางธรณีวิทยาและประวัติศาสตร์ในพื้นที่โครงการ' },
  { factor_id: 'F103', factor_name: 'Provision of permanent additional land', description_th: 'ความเสี่ยงจากการไม่สามารถจัดหาที่ดินเพิ่มเติมอย่างถาวรได้ตามความต้องการของโครงการ' },
  { factor_id: 'F104', factor_name: 'Provision of required land - general', description_th: 'ความเสี่ยงจากความล้มเหลวหรือความล่าช้าในการจัดหาที่ดินที่จำเป็นสำหรับการพัฒนาโครงการโดยทั่วไป' },
  { factor_id: 'F105', factor_name: 'Provision of temporary additional land', description_th: 'ความเสี่ยงจากการไม่สามารถจัดหาที่ดินเพิ่มเติมชั่วคราวได้ เช่น สำหรับพื้นที่พักวัสดุก่อสร้าง' },
  { factor_id: 'F106', factor_name: 'Public Authority Delay Risk', description_th: 'ความเสี่ยงจากความล่าช้าของหน่วยงานราชการในการออกใบอนุญาต อนุมัติ หรือดำเนินการที่จำเป็น' },
  { factor_id: 'F107', factor_name: 'Public opposition to project', description_th: 'ความเสี่ยงจากการคัดค้านหรือต่อต้านของประชาชนและกลุ่มผลประโยชน์ต่อโครงการ' },
  { factor_id: 'F108', factor_name: 'Quality assurance and other construction regulatory standards', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามระบบการประกันคุณภาพและมาตรฐานการก่อสร้างตามข้อกำหนดของหน่วยงานกำกับดูแล' },
  { factor_id: 'F109', factor_name: 'Quality of operation', description_th: 'ความเสี่ยงจากคุณภาพการดำเนินงานและการให้บริการที่ต่ำกว่าระดับที่กำหนดในสัญญา' },
  { factor_id: 'F110', factor_name: 'Quality risk', description_th: 'ความเสี่ยงด้านคุณภาพโดยรวมของโครงการ ทั้งในขั้นตอนการก่อสร้าง การส่งมอบ และการให้บริการระยะยาว' },
  { factor_id: 'F111', factor_name: 'Refinancing', description_th: 'ความเสี่ยงจากความยากในการรีไฟแนนซ์หรือปรับโครงสร้างหนี้ รวมถึงเงื่อนไขที่ไม่เอื้ออำนวยในการรีไฟแนนซ์' },
  { factor_id: 'F112', factor_name: 'Resettlement', description_th: 'ความเสี่ยงจากกระบวนการโยกย้ายและชดเชยค่าทรัพย์สินแก่ผู้ได้รับผลกระทบที่ซับซ้อนและล่าช้า' },
  { factor_id: 'F113', factor_name: 'Residual assets risk', description_th: 'ความเสี่ยงด้านมูลค่าและสภาพของสินทรัพย์คงเหลือเมื่อสิ้นสุดอายุสัมปทานที่ส่งผลต่อการส่งคืน' },
  { factor_id: 'F114', factor_name: 'Risk regarding pricing of product/service', description_th: 'ความเสี่ยงจากการกำหนดราคาสินค้าหรือบริการที่ไม่เหมาะสม ซึ่งกระทบต่อรายได้และความสามารถในการแข่งขัน' },
  { factor_id: 'F115', factor_name: 'Site condition', description_th: 'ความเสี่ยงจากสภาพพื้นที่ก่อสร้างที่ไม่เอื้ออำนวย เช่น ดินอ่อน น้ำใต้ดิน หรือสิ่งกีดขวางที่ไม่คาดคิด' },
  { factor_id: 'F116', factor_name: 'Site security', description_th: 'ความเสี่ยงด้านความปลอดภัยในพื้นที่โครงการ รวมถึงการโจรกรรม การก่อกวน และการบุกรุก' },
  { factor_id: 'F117', factor_name: 'Staff crises', description_th: 'ความเสี่ยงจากวิกฤตด้านบุคลากร เช่น การขาดแคลนพนักงานที่มีทักษะ การลาออกจำนวนมาก หรือการสูญเสียบุคลากรสำคัญ' },
  { factor_id: 'F118', factor_name: 'Strength of Contracting Authority payment covenant', description_th: 'ความเสี่ยงจากความสามารถทางการเงินของหน่วยงานรัฐในการปฏิบัติตามพันธกรณีการชำระเงินตลอดอายุโครงการ' },
  { factor_id: 'F119', factor_name: 'Sub-Contractor failure/insolvency', description_th: 'ความเสี่ยงจากการล้มเหลวหรือการล้มละลายของผู้รับเหมาช่วงที่ส่งผลต่อการดำเนินงานและคุณภาพงาน' },
  { factor_id: 'F120', factor_name: 'Subjective project evaluation method', description_th: 'ความเสี่ยงจากการใช้วิธีประเมินโครงการที่ขาดความเป็นกลาง ไม่โปร่งใส หรืออิงอำนาจดุลยพินิจมากเกินไป' },
  { factor_id: 'F121', factor_name: 'Subsequent planning approvals', description_th: 'ความเสี่ยงจากการไม่ได้รับการอนุมัติแผนงานในขั้นตอนถัดไป ซึ่งอาจล่าช้าหรือหยุดการดำเนินโครงการ' },
  { factor_id: 'F122', factor_name: 'Suitability of design', description_th: 'ความเสี่ยงจากแบบแปลนโครงการที่ไม่เหมาะสมกับวัตถุประสงค์ สภาพแวดล้อม หรือมาตรฐานที่กำหนด' },
  { factor_id: 'F123', factor_name: 'Suitability of land', description_th: 'ความเสี่ยงจากที่ดินที่ไม่มีคุณสมบัติเหมาะสมสำหรับการพัฒนาโครงการตามที่วางแผนไว้' },
  { factor_id: 'F124', factor_name: 'Supporting incentive of government risk', description_th: 'ความเสี่ยงจากการยกเลิก ลด หรือเปลี่ยนแปลงสิทธิประโยชน์และแรงจูงใจที่รัฐบาลให้แก่โครงการ' },
  { factor_id: 'F125', factor_name: 'Tariff change', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงอัตราค่าบริการหรืออัตราภาษีที่ส่งผลกระทบต่อรายได้และความสามารถในการแข่งขัน' },
  { factor_id: 'F126', factor_name: 'Third party tort liability', description_th: 'ความเสี่ยงจากความรับผิดทางแพ่งต่อบุคคลที่สามจากการกระทำละเมิดอันเกิดจากการดำเนินโครงการ' },
  { factor_id: 'F127', factor_name: 'Timing of provision of required land', description_th: 'ความเสี่ยงจากความล่าช้าในการส่งมอบที่ดินที่จำเป็นให้ทันตามกำหนดการโครงการ' },
  { factor_id: 'F128', factor_name: 'Unavailability of insurance', description_th: 'ความเสี่ยงจากการไม่สามารถจัดหาประกันภัยที่จำเป็นในราคาที่สมเหตุสมผล หรือไม่มีผู้รับประกันในตลาด' },
  { factor_id: 'F129', factor_name: 'Unbalanced or inappropriate contractual terms', description_th: 'ความเสี่ยงจากเงื่อนไขสัญญาที่ไม่สมดุล เอื้อฝ่ายใดฝ่ายหนึ่งมากเกินไป หรือไม่สะท้อนการจัดสรรความเสี่ยงที่เหมาะสม' },
  { factor_id: 'F130', factor_name: 'Unclear about state participant portion', description_th: 'ความเสี่ยงจากความไม่ชัดเจนเกี่ยวกับสัดส่วนการมีส่วนร่วม สิทธิ์ และพันธกรณีของรัฐในโครงการ' },
  { factor_id: 'F131', factor_name: 'Uncompetative tender', description_th: 'ความเสี่ยงจากการประมูลที่ไม่มีการแข่งขันเพียงพอ ทำให้เงื่อนไขไม่คุ้มค่าและอาจถูกตั้งคำถามถึงความเป็นธรรม' },
  { factor_id: 'F132', factor_name: 'Unfair process of selection of the private sector', description_th: 'ความเสี่ยงจากกระบวนการคัดเลือกภาคเอกชนที่ไม่เป็นธรรม ไม่โปร่งใส หรือเอื้อประโยชน์แก่ผู้เสนอรายใดรายหนึ่ง' },
  { factor_id: 'F133', factor_name: 'Unproven engineering techniques', description_th: 'ความเสี่ยงจากการนำเทคนิควิศวกรรมที่ยังไม่ผ่านการพิสูจน์ในระดับที่เพียงพอมาใช้ในโครงการ' },
  { factor_id: 'F134', factor_name: 'Unstable government', description_th: 'ความเสี่ยงจากความไม่มั่นคงทางการเมืองและการเปลี่ยนแปลงรัฐบาลบ่อยครั้ง ที่ส่งผลต่อความต่อเนื่องของนโยบายและพันธกรณีของรัฐ' },
  { factor_id: 'F135', factor_name: 'Utilities and installations', description_th: 'ความเสี่ยงจากการรบกวนหรือการย้ายระบบสาธารณูปโภคและการติดตั้งอุปกรณ์ที่มีอยู่เดิมในพื้นที่โครงการ' },
  { factor_id: 'F136', factor_name: 'Vandalism', description_th: 'ความเสี่ยงจากการก่อกวน ทำลาย หรือโจรกรรมทรัพย์สินของโครงการโดยบุคคลภายนอก' },
  { factor_id: 'F137', factor_name: 'Variations Risk', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงขอบเขตงานที่ร้องขอโดยคู่สัญญา ซึ่งส่งผลต่อต้นทุน ระยะเวลา และทรัพยากรของโครงการ' },
  { factor_id: 'F138', factor_name: 'Voluntary Termination by Contracting Authority', description_th: 'ความเสี่ยงจากการที่หน่วยงานรัฐใช้สิทธิ์ยกเลิกสัญญาโดยสมัครใจก่อนครบกำหนด และภาระชดเชยที่ตามมา' },
  { factor_id: 'F139', factor_name: 'Waste of materials', description_th: 'ความเสี่ยงจากการสูญเสียและการใช้วัสดุอย่างไม่มีประสิทธิภาพในการก่อสร้างหรือดำเนินงาน' },
  { factor_id: 'F140', factor_name: 'Weather', description_th: 'ความเสี่ยงจากสภาพอากาศที่ไม่เอื้ออำนวย เช่น ฝนหนัก ความร้อนจัด หรือพายุ ที่ขัดขวางการก่อสร้างและดำเนินงาน' },
  { factor_id: 'F141', factor_name: 'Works completion delays', description_th: 'ความเสี่ยงจากความล่าช้าในการก่อสร้างหรือดำเนินงานให้แล้วเสร็จตามกำหนด ส่งผลต่อการเปิดใช้งานและรายได้' },
] as const

export const RISK_PHASE_OPTIONS = [
  { value: 'pre-construction', label: 'Pre-construction' },
  { value: 'construction', label: 'Construction' },
  { value: 'operation', label: 'Operation' },
] as const

export const MITIGATION_STATUS_OPTIONS = [
  { value: 'planned', label: 'วางแผน (Planned)' },
  { value: 'in_progress', label: 'กำลังดำเนินการ (In Progress)' },
  { value: 'done_or_selected', label: 'ดำเนินการแล้ว / เลือกแล้ว (Done / Selected)' },
  { value: 'rejected', label: 'ไม่ดำเนินการ (Rejected)' },
] as const
