/**
 * Full list of risk factors (F01–F141) for mock/demo when api/v1/info riskFactor is empty.
 * Used by Heat map กลุ่มกิจการ × ปัจจัยความเสี่ยง and anywhere factor names are needed.
 */

export interface RiskFactorMock {
  id: string
  name: string
  description_th: string
}

export const MOCK_RISK_FACTORS: RiskFactorMock[] = [
  { id: 'F01', name: 'Access to the site and associated infrastructure', description_th: 'ความเสี่ยงด้านการเข้าถึงพื้นที่โครงการและโครงสร้างพื้นฐานที่เกี่ยวข้อง เช่น ถนน ระบบสาธารณูปโภค และเส้นทางเข้าออก' },
  { id: 'F02', name: 'Approval of designs', description_th: 'ความเสี่ยงจากความล่าช้าหรือการปฏิเสธในการอนุมัติแบบแปลนจากหน่วยงานที่เกี่ยวข้อง' },
  { id: 'F03', name: 'Asset Ownership Risk (at the end of the contract)', description_th: 'ความเสี่ยงด้านกรรมสิทธิ์ในสินทรัพย์โครงการเมื่อสิ้นสุดสัญญา ว่าจะตกเป็นของฝ่ายใด' },
  { id: 'F04', name: 'Availability of labor/materials', description_th: 'ความเสี่ยงจากการขาดแคลนแรงงานหรือวัสดุที่จำเป็นสำหรับการก่อสร้างหรือดำเนินงาน' },
  { id: 'F05', name: 'Change in Contracting Authority ownership/status', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงกรรมสิทธิ์หรือสถานะขององค์กรภาครัฐที่เป็นคู่สัญญา' },
  { id: 'F06', name: 'Change in law (and taxation)', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงกฎหมายและภาษีที่ส่งผลกระทบต่อต้นทุนหรือการดำเนินงานของโครงการ' },
  { id: 'F07', name: 'Change in Private Partner ownership', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงผู้ถือหุ้นหรือกรรมสิทธิ์ของเอกชนคู่สัญญาที่อาจกระทบต่อการดำเนินโครงการ' },
  { id: 'F08', name: 'Change of scope', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงขอบเขตของโครงการที่ส่งผลต่อต้นทุน ระยะเวลา และคุณภาพ' },
  { id: 'F09', name: 'Changes in industrial code of practices', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงมาตรฐานหรือข้อบังคับในอุตสาหกรรมที่โครงการต้องปฏิบัติตาม' },
  { id: 'F10', name: 'Changes to design', description_th: 'ความเสี่ยงจากการปรับเปลี่ยนแบบแปลนในระหว่างดำเนินโครงการ ซึ่งอาจเพิ่มต้นทุนหรือทำให้ล่าช้า' },
  { id: 'F11', name: 'Climate change event', description_th: 'ความเสี่ยงจากเหตุการณ์ที่เกิดจากการเปลี่ยนแปลงสภาพภูมิอากาศ เช่น อุทกภัย ภัยแล้ง หรือคลื่นความร้อน' },
  { id: 'F12', name: 'Community and businesses', description_th: 'ความเสี่ยงจากผลกระทบของโครงการต่อชุมชนและธุรกิจในพื้นที่ รวมถึงการประท้วงหรือการต่อต้าน' },
  { id: 'F13', name: 'Competition risk', description_th: 'ความเสี่ยงจากการแข่งขันของผู้ให้บริการรายอื่นที่อาจดึงความต้องการและส่งผลต่อรายได้ของโครงการ' },
  { id: 'F14', name: 'Compliance with applicable law', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามกฎหมายและข้อบังคับที่เกี่ยวข้องกับโครงการ' },
  { id: 'F15', name: 'Compliance with environmental consents and laws', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามใบอนุญาตด้านสิ่งแวดล้อมและกฎหมายสิ่งแวดล้อมที่บังคับใช้' },
  { id: 'F16', name: 'Condition At Handback Risk', description_th: 'ความเสี่ยงด้านสภาพของสินทรัพย์โครงการที่อาจไม่เป็นไปตามมาตรฐานที่กำหนดในสัญญาเมื่อถึงเวลาส่งคืน' },
  { id: 'F17', name: 'Condition of facility', description_th: 'ความเสี่ยงด้านสภาพของสิ่งอำนวยความสะดวกที่เสื่อมโทรมหรือไม่เพียงพอ ส่งผลต่อคุณภาพการให้บริการ' },
  { id: 'F18', name: 'Conflicting or imperfect contract', description_th: 'ความเสี่ยงจากข้อขัดแย้งหรือความบกพร่องในสัญญาที่อาจนำไปสู่ข้อพิพาทระหว่างคู่สัญญา' },
  { id: 'F19', name: 'Considerations', description_th: 'ความเสี่ยงจากปัจจัยและเงื่อนไขพิเศษต่าง ๆ ที่ต้องพิจารณาในการดำเนินโครงการ PPP' },
  { id: 'F20', name: 'Consortium inability', description_th: 'ความเสี่ยงจากการที่กลุ่มกิจการร่วมค้าไม่สามารถปฏิบัติตามพันธกรณีที่ตกลงไว้ได้' },
  { id: 'F21', name: 'Contracting Authority default termination', description_th: 'ความเสี่ยงจากการที่หน่วยงานรัฐผิดนัดชำระหนี้หรือผิดสัญญาจนนำไปสู่การยกเลิกสัญญา' },
  { id: 'F22', name: 'Contractor failure/Capability of SPV', description_th: 'ความเสี่ยงจากความล้มเหลวของผู้รับเหมาหลักหรือขีดความสามารถที่ไม่เพียงพอของบริษัทพิเศษเฉพาะกิจ (SPV)' },
  { id: 'F23', name: 'Contractual termination provisions', description_th: 'ความเสี่ยงจากเงื่อนไขการยกเลิกสัญญาที่ไม่ชัดเจนหรือไม่เป็นธรรม ซึ่งอาจสร้างความเสียหายต่อคู่สัญญาฝ่ายใดฝ่ายหนึ่ง' },
  { id: 'F24', name: 'Corruption and lack of respect for law', description_th: 'ความเสี่ยงจากการทุจริตคอร์รัปชัน การติดสินบน และการไม่เคารพต่อกฎหมายในกระบวนการดำเนินโครงการ' },
  { id: 'F25', name: 'Cost increases', description_th: 'ความเสี่ยงจากต้นทุนโครงการที่เพิ่มขึ้นเกินกว่าประมาณการ เนื่องจากราคาวัสดุ แรงงาน หรือปัจจัยอื่น' },
  { id: 'F26', name: 'Cultural differences between main stakeholders', description_th: 'ความเสี่ยงจากความแตกต่างทางวัฒนธรรมและแนวคิดระหว่างผู้มีส่วนได้ส่วนเสียหลักที่ส่งผลต่อการทำงานร่วมกัน' },
  { id: 'F27', name: 'Defects and defective materials', description_th: 'ความเสี่ยงจากข้อบกพร่องในงานก่อสร้างหรือการใช้วัสดุที่ไม่ได้มาตรฐาน ซึ่งส่งผลต่อความทนทานและความปลอดภัย' },
  { id: 'F28', name: 'Delay in approval / permit', description_th: 'ความเสี่ยงจากความล่าช้าในการขออนุมัติหรือใบอนุญาตต่าง ๆ จากหน่วยงานราชการ' },
  { id: 'F29', name: 'Delay in commencement of operations', description_th: 'ความเสี่ยงจากความล่าช้าในการเปิดให้บริการหรือเริ่มต้นดำเนินงานตามกำหนด' },
  { id: 'F30', name: 'Delay in financial closure', description_th: 'ความเสี่ยงจากความล่าช้าในการปิดการจัดหาเงินทุน ซึ่งอาจทำให้โครงการไม่สามารถเริ่มต้นได้ตามแผน' },
  { id: 'F31', name: 'Delay in payment of anuity', description_th: 'ความเสี่ยงจากความล่าช้าในการชำระเงินค่าตอบแทนตามสัญญาจากหน่วยงานรัฐ' },
  { id: 'F32', name: 'Different working methods/know-how between partners', description_th: 'ความเสี่ยงจากความแตกต่างในวิธีการทำงานและองค์ความรู้ระหว่างพันธมิตรภาครัฐและเอกชน' },
  { id: 'F33', name: 'Disputes', description_th: 'ความเสี่ยงจากข้อพิพาทระหว่างคู่สัญญาที่อาจนำไปสู่การฟ้องร้องและส่งผลต่อการดำเนินโครงการ' },
  { id: 'F34', name: 'Disruptive Technology Risk', description_th: 'ความเสี่ยงจากเทคโนโลยีพลิกผันที่เข้ามาแทนที่เทคโนโลยีปัจจุบัน ทำให้โครงการล้าสมัยหรือสูญเสียความสามารถในการแข่งขัน' },
  { id: 'F35', name: 'Environmental conditions caused by the project', description_th: 'ความเสี่ยงจากผลกระทบด้านสิ่งแวดล้อมที่เกิดจากการก่อสร้างหรือดำเนินงานของโครงการ' },
  { id: 'F36', name: 'Exchange rate fluctuation', description_th: 'ความเสี่ยงจากความผันผวนของอัตราแลกเปลี่ยนเงินตราต่างประเทศที่กระทบต้นทุนและรายได้ของโครงการ' },
  { id: 'F37', name: 'Existing asset condition', description_th: 'ความเสี่ยงจากสภาพของสินทรัพย์เดิมที่ไม่เหมาะสมหรือเสื่อมโทรม ซึ่งอาจเพิ่มต้นทุนในการพัฒนา' },
  { id: 'F38', name: 'External environmental events', description_th: 'ความเสี่ยงจากเหตุการณ์ด้านสิ่งแวดล้อมภายนอกที่ไม่สามารถควบคุมได้ เช่น น้ำท่วม แผ่นดินไหว หรือพายุรุนแรง' },
  { id: 'F39', name: 'Financial attraction of project to investors', description_th: 'ความเสี่ยงจากความไม่น่าดึงดูดทางการเงินของโครงการที่ทำให้ยากต่อการระดมทุนจากนักลงทุน' },
  { id: 'F40', name: 'Financiers unwilling to take high risk', description_th: 'ความเสี่ยงจากการที่สถาบันการเงินหรือผู้ให้เงินทุนไม่ยินดีรับความเสี่ยงสูงในโครงการ' },
  { id: 'F41', name: 'Fluctuation of material cost (by government)', description_th: 'ความเสี่ยงจากการผันผวนของราคาวัสดุก่อสร้างอันเนื่องมาจากนโยบายหรือการแทรกแซงของภาครัฐ' },
  { id: 'F42', name: 'Fluctuation of material cost (by private)', description_th: 'ความเสี่ยงจากการผันผวนของราคาวัสดุก่อสร้างอันเนื่องมาจากกลไกตลาดและปัจจัยภาคเอกชน' },
  { id: 'F43', name: 'Force Majeure and Uninsurability termination', description_th: 'ความเสี่ยงจากเหตุสุดวิสัยและการไม่สามารถจัดทำประกันภัยได้ จนนำไปสู่การยกเลิกสัญญาโครงการ' },
  { id: 'F44', name: 'Force majeure consequences', description_th: 'ความเสี่ยงจากผลกระทบที่ตามมาจากเหตุการณ์สุดวิสัย เช่น การหยุดชะงักของโครงการและต้นทุนที่เพิ่มขึ้น' },
  { id: 'F45', name: 'Force majeure events', description_th: 'ความเสี่ยงจากเหตุการณ์สุดวิสัยที่อยู่นอกเหนือการควบคุม เช่น ภัยธรรมชาติ สงคราม การก่อการร้าย หรือโรคระบาด' },
  { id: 'F46', name: 'Frequency of maintenance', description_th: 'ความเสี่ยงจากความถี่ในการบำรุงรักษาที่มากเกินคาดการณ์ ส่งผลต่อต้นทุนดำเนินงานและความพร้อมให้บริการ' },
  { id: 'F47', name: 'General principles', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามหลักการพื้นฐานของโครงการ PPP ที่ดี รวมถึงความโปร่งใสและความรับผิดชอบ' },
  { id: 'F48', name: 'Government support measures', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงหรือการถอนมาตรการสนับสนุนของรัฐบาลที่โครงการพึ่งพาอยู่' },
  { id: 'F49', name: 'Health and safety compliance', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามมาตรฐานด้านสุขภาพและความปลอดภัยในการทำงานและการให้บริการ' },
  { id: 'F50', name: 'Heritage / indigenous land rights', description_th: 'ความเสี่ยงจากการอ้างสิทธิ์ในที่ดินของชนพื้นเมืองหรือมรดกทางวัฒนธรรมที่อาจขัดขวางการพัฒนาโครงการ' },
  { id: 'F51', name: 'Heritage / indigenous people', description_th: 'ความเสี่ยงจากผลกระทบของโครงการต่อชุมชนชนพื้นเมืองและมรดกทางวัฒนธรรมที่ต้องได้รับการคุ้มครอง' },
  { id: 'F52', name: 'High bidding costs', description_th: 'ความเสี่ยงจากต้นทุนการเตรียมการประมูลที่สูงเกินไป ทำให้ผู้สนใจเข้าร่วมประมูลน้อยราย' },
  { id: 'F53', name: 'High finance cost', description_th: 'ความเสี่ยงจากต้นทุนทางการเงินที่สูง เช่น อัตราดอกเบี้ยสูง ค่าธรรมเนียมการจัดการ และค่าใช้จ่ายการระดมทุน' },
  { id: 'F54', name: 'High maintenance cost', description_th: 'ความเสี่ยงจากต้นทุนการบำรุงรักษาที่สูงกว่าประมาณการ ส่งผลต่อความสามารถในการทำกำไรของโครงการ' },
  { id: 'F55', name: 'Higher demand than anticipated', description_th: 'ความเสี่ยงจากความต้องการใช้บริการที่สูงกว่าที่คาดการณ์ ซึ่งอาจกดดันขีดความสามารถและคุณภาพบริการ' },
  { id: 'F56', name: 'Inability to service debt', description_th: 'ความเสี่ยงจากการไม่สามารถชำระดอกเบี้ยหรือเงินต้นได้ตามกำหนด อันเนื่องมาจากกระแสเงินสดไม่เพียงพอ' },
  { id: 'F57', name: 'Inadequate allocation of responsibility and risk', description_th: 'ความเสี่ยงจากการจัดสรรความรับผิดชอบและความเสี่ยงระหว่างภาครัฐและเอกชนที่ไม่เหมาะสม' },
  { id: 'F58', name: 'Inadequate distribution of responsibility and risk', description_th: 'ความเสี่ยงจากการกระจายความรับผิดชอบและภาระความเสี่ยงที่ไม่สมดุลระหว่างคู่สัญญา' },
  { id: 'F59', name: 'Inadequate experience in PPP', description_th: 'ความเสี่ยงจากการขาดประสบการณ์และความเชี่ยวชาญของหน่วยงานรัฐหรือเอกชนในการดำเนินโครงการ PPP' },
  { id: 'F60', name: 'Inadequate feasibility study', description_th: 'ความเสี่ยงจากการศึกษาความเป็นไปได้ที่ไม่ครอบคลุมหรือไม่ถูกต้อง ทำให้ประมาณการต้นทุนและรายได้ผิดพลาด' },
  { id: 'F61', name: 'Inadequate law and supervision system', description_th: 'ความเสี่ยงจากระบบกฎหมายและกลไกการกำกับดูแล PPP ที่ไม่เพียงพอหรือไม่มีประสิทธิภาพ' },
  { id: 'F62', name: 'Inadequate negotiation period prior to initiation', description_th: 'ความเสี่ยงจากระยะเวลาการเจรจาเงื่อนไขสัญญาก่อนเริ่มโครงการที่ไม่เพียงพอ นำไปสู่สัญญาที่บกพร่อง' },
  { id: 'F63', name: 'Increased operating costs and affected performance', description_th: 'ความเสี่ยงจากต้นทุนดำเนินงานที่เพิ่มขึ้นเกินงบประมาณ ส่งผลต่อประสิทธิภาพและคุณภาพการให้บริการ' },
  { id: 'F64', name: 'Industrial action', description_th: 'ความเสี่ยงจากการนัดหยุดงาน การประท้วง หรือการปฏิบัติการทางอุตสาหกรรมของแรงงานที่ขัดขวางโครงการ' },
  { id: 'F65', name: 'Inflation', description_th: 'ความเสี่ยงจากอัตราเงินเฟ้อที่ส่งผลให้ต้นทุนเพิ่มขึ้นและกัดเซาะมูลค่าที่แท้จริงของรายได้โครงการ' },
  { id: 'F66', name: 'Insolvency/default of subcontractors and supplied', description_th: 'ความเสี่ยงจากการล้มละลายหรือผิดนัดชำระหนี้ของผู้รับเหมาช่วงและผู้จัดหาวัสดุ' },
  { id: 'F67', name: 'insufficient income', description_th: 'ความเสี่ยงจากรายได้ที่ไม่เพียงพอต่อการชำระหนี้ ดำเนินงาน และให้ผลตอบแทนแก่ผู้ลงทุน' },
  { id: 'F68', name: 'Intellectual property', description_th: 'ความเสี่ยงด้านทรัพย์สินทางปัญญา สิทธิบัตร และลิขสิทธิ์ที่เกี่ยวข้องกับเทคโนโลยีหรือนวัตกรรมที่ใช้ในโครงการ' },
  { id: 'F69', name: 'Interest rate fluctuation', description_th: 'ความเสี่ยงจากความผันผวนของอัตราดอกเบี้ยที่กระทบต้นทุนการกู้ยืมและความสามารถในการชำระหนี้' },
  { id: 'F70', name: 'Interface', description_th: 'ความเสี่ยงจากการประสานงานและการเชื่อมต่อระหว่างระบบหรือหน่วยงานต่าง ๆ ที่ไม่ราบรื่น' },
  { id: 'F71', name: 'Key planning consents', description_th: 'ความเสี่ยงจากการไม่ได้รับการอนุมัติแผนงานหลักที่จำเป็น ซึ่งอาจหยุดหรือล่าช้าการพัฒนาโครงการ' },
  { id: 'F72', name: 'Lack of commitment from public/private partner', description_th: 'ความเสี่ยงจากการขาดความมุ่งมั่นและความจริงจังของภาครัฐหรือเอกชนในการผลักดันโครงการ' },
  { id: 'F73', name: 'Lack of creditworthiness', description_th: 'ความเสี่ยงจากการขาดความน่าเชื่อถือทางการเงินของคู่สัญญา ทำให้ยากต่อการระดมทุนและการค้ำประกัน' },
  { id: 'F74', name: 'Lack of government guarantees', description_th: 'ความเสี่ยงจากการขาดการค้ำประกันหรือการรับประกันความเสี่ยงจากภาครัฐที่นักลงทุนต้องการ' },
  { id: 'F75', name: 'Lack of transparency in the bidding', description_th: 'ความเสี่ยงจากกระบวนการประมูลที่ขาดความโปร่งใส อาจนำไปสู่ข้อสงสัยและการท้าทายผลการประมูล' },
  { id: 'F76', name: 'Level of demand for the project', description_th: 'ความเสี่ยงจากระดับความต้องการใช้บริการที่แตกต่างอย่างมีนัยสำคัญจากการคาดการณ์ในแบบจำลองทางการเงิน' },
  { id: 'F77', name: 'Liability for death, personal injury, property damage and third party liability', description_th: 'ความเสี่ยงด้านความรับผิดชอบทางกฎหมายจากการเสียชีวิต การบาดเจ็บ ความเสียหายต่อทรัพย์สิน และความรับผิดต่อบุคคลที่สาม' },
  { id: 'F78', name: 'Low capacity of concession company', description_th: 'ความเสี่ยงจากขีดความสามารถด้านการเงิน เทคนิค และการบริหารของบริษัทผู้รับสัมปทานที่ต่ำกว่ามาตรฐาน' },
  { id: 'F79', name: 'Low operating productivity', description_th: 'ความเสี่ยงจากประสิทธิภาพและผลิตภาพในการดำเนินงานที่ต่ำกว่าที่คาดการณ์ ส่งผลต่อต้นทุนและคุณภาพบริการ' },
  { id: 'F80', name: 'Lower demand than anticipated', description_th: 'ความเสี่ยงจากความต้องการใช้บริการที่ต่ำกว่าการคาดการณ์ ส่งผลให้รายได้ไม่เพียงพอต่อการดำเนินโครงการ' },
  { id: 'F81', name: 'MAGA / Change in law termination', description_th: 'ความเสี่ยงจากการยกเลิกสัญญาอันเนื่องมาจากการเปลี่ยนแปลงกฎหมายอย่างมีนัยสำคัญ (Material Adverse Government Action)' },
  { id: 'F82', name: 'Maintenance standards', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามมาตรฐานการบำรุงรักษาที่กำหนดในสัญญา ส่งผลต่อสภาพและอายุการใช้งานของสินทรัพย์' },
  { id: 'F83', name: 'Market demand change', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงของความต้องการตลาดในระยะยาว เช่น การเปลี่ยนพฤติกรรมผู้บริโภคหรือเทคโนโลยีใหม่' },
  { id: 'F84', name: 'Market forecast error', description_th: 'ความเสี่ยงจากความผิดพลาดในการพยากรณ์ตลาดและความต้องการ ซึ่งส่งผลต่อความเป็นไปได้ทางการเงินของโครงการ' },
  { id: 'F85', name: 'Non-involvement of host-community', description_th: 'ความเสี่ยงจากการไม่มีส่วนร่วมของชุมชนท้องถิ่นในกระบวนการวางแผนและตัดสินใจ นำไปสู่การต่อต้าน' },
  { id: 'F86', name: 'Obtaining environmental consents', description_th: 'ความเสี่ยงจากความล่าช้าหรือการไม่ได้รับการอนุมัติด้านสิ่งแวดล้อมที่จำเป็นสำหรับโครงการ' },
  { id: 'F87', name: 'Operational resources or input risk', description_th: 'ความเสี่ยงด้านความพร้อมและต้นทุนของทรัพยากรและปัจจัยการผลิตที่จำเป็นในการดำเนินงาน' },
  { id: 'F88', name: 'Organisation and coordination risk', description_th: 'ความเสี่ยงด้านการจัดองค์กรภายในและการประสานงานระหว่างหน่วยงานต่าง ๆ ที่เกี่ยวข้องกับโครงการ' },
  { id: 'F89', name: 'Performance/ price risk', description_th: 'ความเสี่ยงจากการที่ประสิทธิภาพการให้บริการไม่เป็นไปตามมาตรฐาน หรือการกำหนดราคาที่ไม่เหมาะสม' },
  { id: 'F90', name: 'Permitted Contracting Authority step-in', description_th: 'ความเสี่ยงจากการที่หน่วยงานรัฐใช้สิทธิ์เข้าแทรกแซงการดำเนินงานตามเงื่อนไขสัญญา' },
  { id: 'F91', name: 'Political interference', description_th: 'ความเสี่ยงจากการแทรกแซงทางการเมืองที่ไม่เหมาะสม ส่งผลต่อการตัดสินใจและการดำเนินโครงการ' },
  { id: 'F92', name: 'Political opposition', description_th: 'ความเสี่ยงจากการต่อต้านทางการเมืองต่อโครงการจากฝ่ายค้านหรือกลุ่มผลประโยชน์ต่าง ๆ' },
  { id: 'F93', name: 'Poor project appraisal and selection', description_th: 'ความเสี่ยงจากการประเมินและคัดเลือกโครงการ PPP ที่ขาดความรอบคอบ นำไปสู่การดำเนินโครงการที่ไม่คุ้มค่า' },
  { id: 'F94', name: 'Poor public decision making process', description_th: 'ความเสี่ยงจากกระบวนการตัดสินใจของภาครัฐที่ขาดประสิทธิภาพ ความล่าช้า หรือขาดความโปร่งใส' },
  { id: 'F95', name: 'Poor quality of workmanship', description_th: 'ความเสี่ยงจากคุณภาพฝีมือช่างและการก่อสร้างที่ต่ำกว่ามาตรฐาน ส่งผลต่อความปลอดภัยและความทนทาน' },
  { id: 'F96', name: 'Pre-existing conditions', description_th: 'ความเสี่ยงจากสภาพแวดล้อม ดิน โครงสร้างพื้นฐาน หรือข้อผูกพันที่มีอยู่ก่อนเริ่มโครงการ' },
  { id: 'F97', name: 'Private Partner default termination', description_th: 'ความเสี่ยงจากการที่เอกชนคู่สัญญาผิดนัดพันธกรณีจนถูกบอกเลิกสัญญา ส่งผลต่อความต่อเนื่องของบริการ' },
  { id: 'F98', name: 'Private Partner failure/insolvency', description_th: 'ความเสี่ยงจากการล้มเหลวทางธุรกิจหรือการล้มละลายของเอกชนคู่สัญญาในระหว่างดำเนินโครงการ' },
  { id: 'F99', name: 'Private Partner not to be fincially or technically capable implement the project.', description_th: 'ความเสี่ยงจากการที่เอกชนคู่สัญญาขาดความสามารถทางการเงินหรือความเชี่ยวชาญทางเทคนิคที่จำเป็นสำหรับโครงการ' },
  { id: 'F100', name: 'Project management and interface with other works/facilities', description_th: 'ความเสี่ยงด้านการบริหารจัดการโครงการและการประสานงานกับงานก่อสร้างหรือสิ่งอำนวยความสะดวกอื่นที่ดำเนินการควบคู่กัน' },
  { id: 'F101', name: 'Project operation change', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงรูปแบบหรือขอบเขตการดำเนินงานโครงการที่ส่งผลต่อต้นทุนและรายได้' },
  { id: 'F102', name: 'Protection of geological and historical objects', description_th: 'ความเสี่ยงจากการค้นพบโบราณวัตถุหรือสิ่งสำคัญทางธรณีวิทยาและประวัติศาสตร์ในพื้นที่โครงการ' },
  { id: 'F103', name: 'Provision of permanent additional land', description_th: 'ความเสี่ยงจากการไม่สามารถจัดหาที่ดินเพิ่มเติมอย่างถาวรได้ตามความต้องการของโครงการ' },
  { id: 'F104', name: 'Provision of required land - general', description_th: 'ความเสี่ยงจากความล้มเหลวหรือความล่าช้าในการจัดหาที่ดินที่จำเป็นสำหรับการพัฒนาโครงการโดยทั่วไป' },
  { id: 'F105', name: 'Provision of temporary additional land', description_th: 'ความเสี่ยงจากการไม่สามารถจัดหาที่ดินเพิ่มเติมชั่วคราวได้ เช่น สำหรับพื้นที่พักวัสดุก่อสร้าง' },
  { id: 'F106', name: 'Public Authority Delay Risk', description_th: 'ความเสี่ยงจากความล่าช้าของหน่วยงานราชการในการออกใบอนุญาต อนุมัติ หรือดำเนินการที่จำเป็น' },
  { id: 'F107', name: 'Public opposition to project', description_th: 'ความเสี่ยงจากการคัดค้านหรือต่อต้านของประชาชนและกลุ่มผลประโยชน์ต่อโครงการ' },
  { id: 'F108', name: 'Quality assurance and other construction regulatory standards', description_th: 'ความเสี่ยงจากการไม่ปฏิบัติตามระบบการประกันคุณภาพและมาตรฐานการก่อสร้างตามข้อกำหนดของหน่วยงานกำกับดูแล' },
  { id: 'F109', name: 'Quality of operation', description_th: 'ความเสี่ยงจากคุณภาพการดำเนินงานและการให้บริการที่ต่ำกว่าระดับที่กำหนดในสัญญา' },
  { id: 'F110', name: 'Quality risk', description_th: 'ความเสี่ยงด้านคุณภาพโดยรวมของโครงการ ทั้งในขั้นตอนการก่อสร้าง การส่งมอบ และการให้บริการระยะยาว' },
  { id: 'F111', name: 'Refinancing', description_th: 'ความเสี่ยงจากความยากในการรีไฟแนนซ์หรือปรับโครงสร้างหนี้ รวมถึงเงื่อนไขที่ไม่เอื้ออำนวยในการรีไฟแนนซ์' },
  { id: 'F112', name: 'Resettlement', description_th: 'ความเสี่ยงจากกระบวนการโยกย้ายและชดเชยค่าทรัพย์สินแก่ผู้ได้รับผลกระทบที่ซับซ้อนและล่าช้า' },
  { id: 'F113', name: 'Residual assets risk', description_th: 'ความเสี่ยงด้านมูลค่าและสภาพของสินทรัพย์คงเหลือเมื่อสิ้นสุดอายุสัมปทานที่ส่งผลต่อการส่งคืน' },
  { id: 'F114', name: 'Risk regarding pricing of product/service', description_th: 'ความเสี่ยงจากการกำหนดราคาสินค้าหรือบริการที่ไม่เหมาะสม ซึ่งกระทบต่อรายได้และความสามารถในการแข่งขัน' },
  { id: 'F115', name: 'Site condition', description_th: 'ความเสี่ยงจากสภาพพื้นที่ก่อสร้างที่ไม่เอื้ออำนวย เช่น ดินอ่อน น้ำใต้ดิน หรือสิ่งกีดขวางที่ไม่คาดคิด' },
  { id: 'F116', name: 'Site security', description_th: 'ความเสี่ยงด้านความปลอดภัยในพื้นที่โครงการ รวมถึงการโจรกรรม การก่อกวน และการบุกรุก' },
  { id: 'F117', name: 'Staff crises', description_th: 'ความเสี่ยงจากวิกฤตด้านบุคลากร เช่น การขาดแคลนพนักงานที่มีทักษะ การลาออกจำนวนมาก หรือการสูญเสียบุคลากรสำคัญ' },
  { id: 'F118', name: 'Strength of Contracting Authority payment covenant', description_th: 'ความเสี่ยงจากความสามารถทางการเงินของหน่วยงานรัฐในการปฏิบัติตามพันธกรณีการชำระเงินตลอดอายุโครงการ' },
  { id: 'F119', name: 'Sub-Contractor failure/insolvency', description_th: 'ความเสี่ยงจากการล้มเหลวหรือการล้มละลายของผู้รับเหมาช่วงที่ส่งผลต่อการดำเนินงานและคุณภาพงาน' },
  { id: 'F120', name: 'Subjective project evaluation method', description_th: 'ความเสี่ยงจากการใช้วิธีประเมินโครงการที่ขาดความเป็นกลาง ไม่โปร่งใส หรืออิงอำนาจดุลยพินิจมากเกินไป' },
  { id: 'F121', name: 'Subsequent planning approvals', description_th: 'ความเสี่ยงจากการไม่ได้รับการอนุมัติแผนงานในขั้นตอนถัดไป ซึ่งอาจล่าช้าหรือหยุดการดำเนินโครงการ' },
  { id: 'F122', name: 'Suitability of design', description_th: 'ความเสี่ยงจากแบบแปลนโครงการที่ไม่เหมาะสมกับวัตถุประสงค์ สภาพแวดล้อม หรือมาตรฐานที่กำหนด' },
  { id: 'F123', name: 'Suitability of land', description_th: 'ความเสี่ยงจากที่ดินที่ไม่มีคุณสมบัติเหมาะสมสำหรับการพัฒนาโครงการตามที่วางแผนไว้' },
  { id: 'F124', name: 'Supporting incentive of government risk', description_th: 'ความเสี่ยงจากการยกเลิก ลด หรือเปลี่ยนแปลงสิทธิประโยชน์และแรงจูงใจที่รัฐบาลให้แก่โครงการ' },
  { id: 'F125', name: 'Tariff change', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงอัตราค่าบริการหรืออัตราภาษีที่ส่งผลกระทบต่อรายได้และความสามารถในการแข่งขัน' },
  { id: 'F126', name: 'Third party tort liability', description_th: 'ความเสี่ยงจากความรับผิดทางแพ่งต่อบุคคลที่สามจากการกระทำละเมิดอันเกิดจากการดำเนินโครงการ' },
  { id: 'F127', name: 'Timing of provision of required land', description_th: 'ความเสี่ยงจากความล่าช้าในการส่งมอบที่ดินที่จำเป็นให้ทันตามกำหนดการโครงการ' },
  { id: 'F128', name: 'Unavailability of insurance', description_th: 'ความเสี่ยงจากการไม่สามารถจัดหาประกันภัยที่จำเป็นในราคาที่สมเหตุสมผล หรือไม่มีผู้รับประกันในตลาด' },
  { id: 'F129', name: 'Unbalanced or inappropriate contractual terms', description_th: 'ความเสี่ยงจากเงื่อนไขสัญญาที่ไม่สมดุล เอื้อฝ่ายใดฝ่ายหนึ่งมากเกินไป หรือไม่สะท้อนการจัดสรรความเสี่ยงที่เหมาะสม' },
  { id: 'F130', name: 'Unclear about state participant portion', description_th: 'ความเสี่ยงจากความไม่ชัดเจนเกี่ยวกับสัดส่วนการมีส่วนร่วม สิทธิ์ และพันธกรณีของรัฐในโครงการ' },
  { id: 'F131', name: 'Uncompetative tender', description_th: 'ความเสี่ยงจากการประมูลที่ไม่มีการแข่งขันเพียงพอ ทำให้เงื่อนไขไม่คุ้มค่าและอาจถูกตั้งคำถามถึงความเป็นธรรม' },
  { id: 'F132', name: 'Unfair process of selection of the private sector', description_th: 'ความเสี่ยงจากกระบวนการคัดเลือกภาคเอกชนที่ไม่เป็นธรรม ไม่โปร่งใส หรือเอื้อประโยชน์แก่ผู้เสนอรายใดรายหนึ่ง' },
  { id: 'F133', name: 'Unproven engineering techniques', description_th: 'ความเสี่ยงจากการนำเทคนิควิศวกรรมที่ยังไม่ผ่านการพิสูจน์ในระดับที่เพียงพอมาใช้ในโครงการ' },
  { id: 'F134', name: 'Unstable government', description_th: 'ความเสี่ยงจากความไม่มั่นคงทางการเมืองและการเปลี่ยนแปลงรัฐบาลบ่อยครั้ง ที่ส่งผลต่อความต่อเนื่องของนโยบายและพันธกรณีของรัฐ' },
  { id: 'F135', name: 'Utilities and installations', description_th: 'ความเสี่ยงจากการรบกวนหรือการย้ายระบบสาธารณูปโภคและการติดตั้งอุปกรณ์ที่มีอยู่เดิมในพื้นที่โครงการ' },
  { id: 'F136', name: 'Vandalism', description_th: 'ความเสี่ยงจากการก่อกวน ทำลาย หรือโจรกรรมทรัพย์สินของโครงการโดยบุคคลภายนอก' },
  { id: 'F137', name: 'Variations Risk', description_th: 'ความเสี่ยงจากการเปลี่ยนแปลงขอบเขตงานที่ร้องขอโดยคู่สัญญา ซึ่งส่งผลต่อต้นทุน ระยะเวลา และทรัพยากรของโครงการ' },
  { id: 'F138', name: 'Voluntary Termination by Contracting Authority', description_th: 'ความเสี่ยงจากการที่หน่วยงานรัฐใช้สิทธิ์ยกเลิกสัญญาโดยสมัครใจก่อนครบกำหนด และภาระชดเชยที่ตามมา' },
  { id: 'F139', name: 'Waste of materials', description_th: 'ความเสี่ยงจากการสูญเสียและการใช้วัสดุอย่างไม่มีประสิทธิภาพในการก่อสร้างหรือดำเนินงาน' },
  { id: 'F140', name: 'Weather', description_th: 'ความเสี่ยงจากสภาพอากาศที่ไม่เอื้ออำนวย เช่น ฝนหนัก ความร้อนจัด หรือพายุ ที่ขัดขวางการก่อสร้างและดำเนินงาน' },
  { id: 'F141', name: 'Works completion delays', description_th: 'ความเสี่ยงจากความล่าช้าในการก่อสร้างหรือดำเนินงานให้แล้วเสร็จตามกำหนด ส่งผลต่อการเปิดใช้งานและรายได้' },
]

/** All risk factor IDs F01..F141 in order (for heatmap columns). */
export const ALL_RISK_FACTOR_IDS = MOCK_RISK_FACTORS.map((f) => f.id)
